apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "watcher.stakater.com.stakater.com/v1alpha1",
          "kind": "ResourceWatcher",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "stakater-operator-boilerplate",
              "app.kubernetes.io/instance": "resourcewatcher-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "resourcewatcher",
              "app.kubernetes.io/part-of": "stakater-operator-boilerplate"
            },
            "name": "resourcewatcher-sample"
          },
          "spec": {
            "watchSecrets": true
          }
        },
        {
          "apiVersion": "watcher.stakater.com.stakater.com/v1alpha1",
          "kind": "StatusUpdater",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "stakater-operator-boilerplate",
              "app.kubernetes.io/instance": "statusupdater-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "statusupdater",
              "app.kubernetes.io/part-of": "stakater-operator-boilerplate"
            },
            "name": "statusupdater-sample"
          },
          "spec": {
            "incidents": [
              {
                "message": "I completed a task",
                "reason": "Success",
                "type": "SuccessType"
              },
              {
                "message": "I failed a task",
                "reason": "Failed",
                "type": "FailedType"
              },
              {
                "message": "I failed another task",
                "reason": "Failed",
                "type": "FailedAgain"
              }
            ]
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.25.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: stakater-operator-boilerplate.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - displayName: Resource Watcher
      kind: ResourceWatcher
      name: resourcewatchers.watcher.stakater.com.stakater.com
      version: v1alpha1
    - displayName: Status Updater
      kind: StatusUpdater
      name: statusupdaters.watcher.stakater.com.stakater.com
      version: v1alpha1
  description: Example operator project
  displayName: Operator boilerplate
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - watcher.stakater.com.stakater.com
          resources:
          - statusupdaters
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - watcher.stakater.com.stakater.com
          resources:
          - statusupdaters/finalizers
          verbs:
          - update
        - apiGroups:
          - watcher.stakater.com.stakater.com
          resources:
          - statusupdaters/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: stakater-operator-boilerplate-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: stakater-operator-boilerplate
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: stakater-operator-boilerplate
          control-plane: controller-manager
        name: stakater-operator-boilerplate-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: docker.io/stakaterdockerhubpullroot/operator-boilerplate:v0.0.1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: stakater-operator-boilerplate-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: stakater-operator-boilerplate-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - operator-sdk
  - openshift
  - kubernetes
  links:
  - name: Stakater Operator Boilerplate
    url: https://stakater-operator-boilerplate.domain
  maturity: alpha
  provider:
    name: Stakater AB
    url: https://www.stakater.com
  version: 0.0.1
