apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: stakater-operator-boilerplate
  namespace: openshift-marketplace
spec:
  displayName: Stakater Operator Boilerplate
  publisher: Stakater AB
  sourceType: grpc
  image: stakaterdockerhubpullroot/operator-boilerplate-catalog:v0.0.1
  updateStrategy:
    registryPoll:
      interval: 30m