apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: operator-boilerplate
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: operator-boilerplate
  source: operator-boilerplate
  sourceNamespace: openshift-marketplace
  startingCSV: operator-boilerplate.v0.0.1