# permissions for end users to view resourcewatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: resourcewatcher-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-boilerplate
    app.kubernetes.io/part-of: operator-boilerplate
    app.kubernetes.io/managed-by: kustomize
  name: resourcewatcher-viewer-role
rules:
- apiGroups:
  - watcher.stakater.com.stakater.com
  resources:
  - resourcewatchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - watcher.stakater.com.stakater.com
  resources:
  - resourcewatchers/status
  verbs:
  - get
