# permissions for end users to edit resourcewatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: resourcewatcher-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: stakater-operator-boilerplate
    app.kubernetes.io/part-of: stakater-operator-boilerplate
    app.kubernetes.io/managed-by: kustomize
  name: resourcewatcher-editor-role
rules:
- apiGroups:
  - watcher.stakater.com.stakater.com
  resources:
  - resourcewatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - watcher.stakater.com.stakater.com
  resources:
  - resourcewatchers/status
  verbs:
  - get
