# permissions for end users to edit statusupdaters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: statusupdater-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-boilerplate
    app.kubernetes.io/part-of: operator-boilerplate
    app.kubernetes.io/managed-by: kustomize
  name: statusupdater-editor-role
rules:
- apiGroups:
  - watcher.stakater.com.stakater.com
  resources:
  - statusupdaters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - watcher.stakater.com.stakater.com
  resources:
  - statusupdaters/status
  verbs:
  - get
