apiVersion: watcher.stakater.com.stakater.com/v1alpha1
kind: StatusUpdater
metadata:
  labels:
    app.kubernetes.io/name: statusupdater
    app.kubernetes.io/instance: statusupdater-sample
    app.kubernetes.io/part-of: operator-boilerplate
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator-boilerplate
  name: statusupdater-sample
spec:
  incidents:
    - type: "SuccessType"
      reason: "Success"
      message: "I completed a task"
    - type: "FailedType"
      reason: "Failed"
      message: "I failed a task"
    - type: "FailedAgain"
      reason: "Failed"
      message: "I failed another task"
